apiVersion: v1
data:
  BROKER_URL: amqp://<mq-user>:<ma-password>@<mq-server>:<mq-port>
  QUEUE: <mq-queue-for-file-listinf>
  CSV_INPUT: <accessible csv http(s) URL>
  AWS_ACCESS_KEY: aaaaaaa 
  AWS_SECRET_KEY: adasdasdasdasdasd
  S3_ENDPOINT: <s3 endpoint with http(s)>
  S3_OUTPUT_BUCKET: <s3 bucket>
  S3_OUTPUT_FILEPATH: <s3 path>
  HTTP_PROXY: <proxy>
  HTTPS_PROXY: <proxy>
  http_proxy: <proxy>
  https_proxy: <proxy>
  no_proxy: localhost,.cluster.local,.minio
  NO_PROXY: localhost,.cluster.local,.minio
kind: ConfigMap
metadata:
  name: indexer-config
