apiVersion: batch/v1
kind: Job
metadata:
  name: job-file-ingesting-1
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: job-file-ingesting-1 
    spec:
      #imagePullSecrets:
      #  - name: registry-secret
      containers:
      - name: c
        image: ebitsi/dsds-indexer-file-ingesting
        envFrom:
         - configMapRef:
             name: indexer-config
        volumeMounts:
        - name: data
          mountPath: /data/
      restartPolicy: OnFailure
      volumes:
      - name: data
        emptyDir: {}

