apiVersion: batch/v1
kind: Job
metadata:
  name: job-file-listing-1
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: job-file-listing-1 
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: c
        image: ebitsi/dsds-indexer-file-listing
        envFrom:
         - configMapRef:
             name: indexer-config
      restartPolicy: OnFailure

