apiVersion: batch/v1
kind: Job
metadata:
  name: job-wq-1
spec:
  completions: 8
  parallelism: 2
  template:
    metadata:
      name: job-wq-1
    spec:
      imagePullSecrets:
        - name: gitlab-registry-secret
      containers:
      - name: c
        image: dockerhub.ebi.ac.uk/soumyadip/dsds-indexer/file-list
        envFrom:
         - configMapRef:
             name: indexer-config
      restartPolicy: OnFailure