stages:
  - build
  - deploy
  - extract
  - report

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR/k8s-job/worker-image --destination $CI_REGISTRY_IMAGE-worker:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR/k8s-job/file-list-image --destination $CI_REGISTRY_IMAGE-file-list:$CI_COMMIT_TAG

deploy:
  stage: deploy
  image:
    name: roffe/kubectl
  script:
    - kubectl -n ${KUBE_NAMESPACE} apply -f ${INDEXER_CONFIGMAP} 
    - kubectl -n ${KUBE_NAMESPACE} delete -f k8s-job/job/job.yaml | kubectl -n ${KUBE_NAMESPACE} apply -f k8s-job/job/job.yaml
    - kubectl -n ${KUBE_NAMESPACE} describe job/job-wq-1

    
.extract-metabolights:
  image: "python:3.5"
  stage: extract
  before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  script:
    - python scripts/extract-omicsdi-datasets.py metabolights
  artifacts:
    paths:
    - data/metabolights.csv
    expire_in: 1 week

.extract-pride:
  image: "python:3.5"
  stage: extract
  before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  script:
    - python scripts/extract-omicsdi-datasets.py pride
  artifacts:
    paths:
    - data/pride.csv
    expire_in: 1 week

.extract-arrayexpress:
  image: "python:3.5"
  stage: extract
  before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  script:
    - python scripts/extract-omicsdi-datasets.py arrayexpress
  artifacts:
    paths:
    - data/arrayexpress.csv
    expire_in: 1 week

.extract-eva:
  image: "python:3.5"
  stage: extract
  before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  script:
    - python scripts/extract-omicsdi-datasets.py eva
  artifacts:
    paths:
    - data/eva.csv
    expire_in: 1 week

.extract-expression-atlas:
  image: "python:3.5"
  stage: extract
  before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  script:
    - python scripts/extract-omicsdi-datasets.py expression-atlas
  artifacts:
    paths:
    - data/expression-atlas.csv
    expire_in: 1 week

.report:
  image: "alpine"
  stage: report
  script:
    - wc -l data/*.csv | tee data/report.txt
  artifacts:
    paths:
    - data/