stages:
  - extract
  - report

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

extract-eva:
  image: "python:3.5"
  stage: extract
  script:
    - python scripts/extract-omicsdi-datasets.py eva

extract-metabolights:
  image: "python:3.5"
  stage: extract
  script:
    - python scripts/extract-omicsdi-datasets.py metabolights

report:
  image: "python:3.5"
  stage: report
  script:
    - wc -l data/*.csv