stages:
  - extract
  - report

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt

extract-eva:
  image: "python:3.5"
  stage: extract
  script:
    - python scripts/extract-omicsdi-datasets.py eva
  artifacts:
    paths:
    - data/eva.csv
    expire_in: 1 week

extract-metabolights:
  image: "python:3.5"
  stage: extract
  script:
    - python scripts/extract-omicsdi-datasets.py metabolights
  artifacts:
    paths:
    - data/metabolights.csv
    expire_in: 1 week

report:
  image: "python:3.5"
  stage: report
  dependencies:
    - extract-eva
    - extract-metabolights
  script:
    - wc -l data/*.csv